### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by flosse** [dtolnay/paste#103]
This is not a bug report, but it's important enough to make an issue :stuck_out_tongue_winking_eye: 

I am an open source maintainer myself and I know that most people only get in touch when something doesn't work.
So here's the other way around: it works wonderfully and allows me to write powerful macros :smile: 

So at this point I just want to say: Thank you very much! ❤️

**Comment by dtolnay** [comment]
Cheers -- I appreciate the note.
