### ISSUE TITLE
Identifier case conversion

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/paste#13]
Use case provided to me by email:

```rust
macro_rules! ld_r16_expr {
    ($($reg:ident)*) => {
        $(
            paste::item! {
                pub fn [<ld_ $reg _expr>] (val: Expr) -> Token {
                    token_for_opcode_two_args(
                        Mnemonic::Ld,
                        Register16::$reg.into(),
                        val.into(),
                    )
                }
            }
        )*
    }
}

ld_r16_expr!(Af Bc De Hl);
```

We would like some way to end up with functions `ld_af_expr` `ld_bc_expr` etc rather than `ld_Af_expr` `ld_Bc_expr`.

I would be be prepared to consider a PR implementing this as something like `[<ld_ $reg:lower _expr>]`.

**Comment by wdanilo** [comment]
I just went to this repo to ask exactly about this feature! The `paste` macro is amazing. If it would allow for that, it would be just amazing * 100 <3

**Comment by dtolnay** [comment]
Paste 0.1.8 has added support for `$var:lower`. I'll keep this open and we may add support for other case modifiers as people need them.

**Comment by rozaliev** [comment]
@dtolnay, is it intentional that 0.1.8 is not published on crates.io?

**Comment by dtolnay** [comment]
Oops, published paste-impl but not paste. Fixed now.

**Comment by dtolnay** [comment]
I think we can close this issue at this point. We now support `:lower`, `:upper`, and `:snake` case as covered in https://github.com/dtolnay/paste/tree/0.1.10#case-conversion.
