### ISSUE TITLE
can't concat namespace

### ISSUE THREAD

**Issue by s97712** [dtolnay/paste#16]
I tried concat namespace using following code

```rs
macro_rules! call {
  ($path: expr) => {
    [<$path::call>]()
  };
}
```

And get compile error
```
error: expected `::`, found `]`
  --> .../src/lib.rs:20:11
   |
20 |           [<$path::call>]()
   |           ^^^^^^^^^^^^^^^ expected `::`

```
Consider supporting namespace ?

**Comment by dtolnay** [comment]
I would prefer to stick to concatenating identifiers, but someone could make a different crate focused on paths.

FWIW you don't need a proc macro to concatenate paths if you use `$($seg:ident)::*` instead of expr.
