### ISSUE TITLE
CamelCase conversion

### ISSUE THREAD

**Issue by mcatanzariti** [dtolnay/paste#22]
Hi,

I need the exact opposite of `$var:snake`:
`$var:camel` to convert snake_case input to CamelCase 

Thank you for your great work!

**Comment by thedavidmeister** [comment]
yes, i just came here to say the same thing!

**Comment by thedavidmeister** [comment]
also i think technically it is `PascalCase` not `camelCase`

https://clj-commons.org/camel-snake-kebab/
