### ISSUE TITLE
Add repository topics

### ISSUE THREAD

**Issue by thedrow** [dtolnay/paste#24]
I'll probably forget that this exists by the time I'll need it so let's make this repository more discoverable :)

**Comment by dtolnay** [comment]
Would you be able to suggest some topics that would be useful? I haven't been using topics for most of my repos.

**Comment by thedrow** [comment]
I guess `rust`, `library` and `macros` would be a good start.

**Comment by dtolnay** [comment]
I added <kbd>pound pound</kbd> to help people searching for C preprocessor's `##`.

The suggestions in https://github.com/dtolnay/paste/issues/24#issuecomment-623943557 are all present in the readme already.
