### ISSUE TITLE
Add copyright holder to LICENSE-MIT?

### ISSUE THREAD

**Issue by eoger** [dtolnay/paste#28]
Looking at [LICENSE-MIT](https://github.com/dtolnay/paste/blob/master/LICENSE-MIT), the file starts with `Copyright (c) 2018`, shouldn't it be `Copyright (c) 2018 David Tolnay`? [0]

[0] https://opensource.org/licenses/MIT

**Comment by dtolnay** [comment]
That whole line is actually meaningless, with or without a name on it. See e.g. https://github.com/rust-lang/rust/blob/1.43.0/LICENSE-MIT which leaves it out entirely, which I have started to do in other projects.

**Comment by eoger** [comment]
No worries, thanks!
