### ISSUE TITLE
Macro Expansion on Windows Stable Fails

### ISSUE THREAD

**Issue by inspier** [dtolnay/paste#41]
I am getting `error[E0658]: procedural macros cannot be expanded to statements` and `error[E0658]: procedural macros cannot be expanded to expressions` for these two macros respectively only on Windows Stable. Not sure if this is a known limitation, but was just curious.

```rust
#[macro_export]
macro_rules! set {
    ($self:ident, $field:ident, $value:expr) => {
        paste::item! {
            $self.[<set_ $field:snake>]($value)
        }
    };
}

#[macro_export]
macro_rules! get {
    ($self:ident, $field:ident) => {
        paste::item! {
            $self.[<get_ $field:snake>]()
        }
    };
}
```

**Comment by dtolnay** [comment]
Hi @inspier, for an expression (which `self.set_field(value)` is) you would need to use paste::expr as described in https://github.com/dtolnay/paste#pasting-identifiers.
