### ISSUE TITLE
Feature requests: Concatenate integer literals & create identifiers based on a given range

### ISSUE THREAD

**Issue by bradleyharden** [dtolnay/paste#53]
I have two feature requests, but I'm not sure if either is within the scope of this crate. Both are motivated by the same example. I'm working in an embedded context, writing a module for GPIO pins. The pins are in four groups of 32, labeled PA00-PA31, PB00-PB31, PC00-PC31 and PD00-PD31. Within a macro, I generate marker types for each pin, and each one implements a `PinId` trait with an associated constant containing the pin group (A-D) and pin number (0-31).

Right now, I supply the pin name and number as a tuple containing an identifier and a literal, like this

```rust
[
    (PA00, 00),
    // ...
    (PA31, 31),
]
```

But that approach is redundant and error prone. It would be really nice if there were a way to concatenate the integer literal, so the macro call could look like this

```rust
PA: [
    00,
    // ...
    31,
]
```

Within the macro, I'm imagining a syntax like this

```rust
( $prefix:ident: [ $( $num:literal, )+ ] ) => {
    paste! {
        enum [<$prefix $num:2>] {}
        impl PinId for [<$prefix $num:2>] {
            const NUM: u8 = $num;
        }
    }
}
```

The `:2` here tells `paste` to print the literal with a width of two, where zero padding is implied.

I've thought through some of the potential problems and didn't see any showstoppers. For instance, I think it only makes sense to support unsigned integer literals. Negative or floating point numbers wouldn't make any sense. I suppose you could also accept string literals, but that seems pointless compared to an identifier. When converting the integer literal to an identifier, it would be nice if you could specify a field width. Zero padding would be implied, because spaces can't be part of an identifier. If the integer doesn't fit within the specified width, it should be a compile-time error. If possible, I would also like to see hex output supported, so something like this `[<$prefix $num:hex:2>]`.

Is this within the scope of `paste`?

To simplify the previous example even more, would it be possible to create all possible identifiers within a given range? Something like this

```rust
PA: (0..32)
```

I also have a use case for letters, where alternate peripheral pin functions are labeled `AlternateA` through `AlternateN`. It would be better if I didn't have to write out all of them

```rust
Alternate: ('A'..='N')
```

I feel like concatenating integer literals is fairly straightforward, but I'm much less certain about this feature. First of all, you would have to create a repeating unit within a macro where it didn't exist previously, which may not be possible. Or maybe alternatively, you write it like this

```rust
( $prefix:ident: ( $( $range:literal, )+ ) ) => {
    paste! {
        $(
            enum [<$prefix $range:2>] {}
        )+
    }
}
```

And call it like this

```rust
PA: (00, 31,)
```

In this case, there is already a repeating `$()+`. `paste` is just transforming it from length 2 to length 32. But again, this may not be possible.

Is there any reasonable way to generate a range of identifiers like this?

**Comment by dtolnay** [comment]
This is in scope for the https://github.com/dtolnay/seq-macro crate more than this one. You'll want to do something like:

```rust
// [dependencies]
// seq-macro = "0.2"

use seq_macro::seq;

pub trait PinId {
    const NUM: u8;
}

seq!(G in 'A'..='D' {
    seq!(N in 00..=31 {
        pub enum P#G#N {}
        impl PinId for P#G#N {
            const NUM: u8 = N;
        }
    });
});
```

**Comment by bradleyharden** [comment]
Wow, ok. I didn't realize that what I wanted already existed. Thanks
