### ISSUE TITLE
Compile error with old Glibc?

### ISSUE THREAD

**Issue by piegamesde** [dtolnay/paste#79]
My CI just failed with this (after no apparent change)

```
error: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /__w/target/release/deps/libpaste-9f4ba831280a7332.so)
  --> /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/simba-0.7.1/src/scalar/complex.rs:23:9
   |
23 |         paste::item! {
   |         ^^^^^

error: cannot determine resolution for the macro `paste::item`
```

The code runs on a Fedora 34 which ships glibc 2.33 (IIRC), so it makes sense. Would you please confirm that a recent change increased the minimum required version? (Because otherwise I'd seriously confused about how any of this ever worked before)

**Comment by dtolnay** [comment]
I don't know of any recent changes or even any code in this crate that would be able to cause an issue like that. Whatever changed is somewhere else.
