### ISSUE TITLE
Access to variable declared in macro

### ISSUE THREAD

**Issue by BratSinot** [dtolnay/paste#80]
Greetings!

I don't know, maybe it related with #7, but I can't use variable from macro:
```rust
use paste::paste;

macro_rules! gen {
    ( $name:tt, $plural:tt ) => {
        paste! {
            let [<$name $plural _str >] = stringify!([<Str $name:camel $plural>]);
        }
    };
}

fn main() {
    gen!("foo", "s");

    println!("{}", foos_str);
}
```

I'm getting:
```log
error[E0425]: cannot find value `foos_str` in this scope
  --> src/main.rs:14:20
   |
14 |     println!("{}", foos_str);
   |                    ^^^^^^^^ not found in this scope
```

**Comment by dtolnay** [comment]
This is the correct behavior.

Your macro is basically like the example macro in the explanation on this page: https://danielkeep.github.io/tlborm/book/mbe-min-hygiene.html.

**Comment by BratSinot** [comment]
> macro is basically like the example macro in the explanation on this

I guessed that it was in scope, but any way to get around this without `let var = macro!();`?

**Comment by dtolnay** [comment]
Yeah, you can make `gen` a proc macro and make it declare the local with a call site span.

I'll close this issue since `paste` wouldn't be involved at that point.
