### ISSUE TITLE
Wishlist: local token identifiers?

### ISSUE THREAD

**Issue by jsgf** [dtolnay/paste#81]
I have some uses of `paste` where the same set of token pastes are repeated a few times. For example, within a macro_rules:
```
paste::paste! {
    struct [<$name:camel Struct>] {
      // ...
    }

    impl [<$name:camel Struct>] {
       // ...
    }

    impl SomeTrait for [<$name:camel Struct>] { ... }
}
```

It would be nice to have a mechanism to locally define a symbol representing the `[<$name:camel Struct>]` token pasting expression. I could add a new layer of macro expansion to capture that expression, but that doesn't feel like a great solution.

Is there some other existing idiom for this?

If not, then as a total straw-man suggestion for syntax, maybe something like:
```
paste::paste! {
    paste::define!(structname, [<$name:camel Struct>]);

    struct $structname {
    ...
```

**Comment by banool** [comment]
Hey @jsgf! I'd love this as well, I find myself repeating the same thing a lot.

**Comment by dtolnay** [comment]
I think I would prefer not to support this in this crate. But anybody else should feel free to experiment with a more fully featured crate that can do this kind of thing.
