### ISSUE TITLE
Lifetime idents support

### ISSUE THREAD

**Issue by tqwewe** [dtolnay/paste#89]
Is it possible to create lifetimes with paste?

For example:
```rust
macro_rules! impl_types {
    ( $($ty:ident),* ) => {
        paste::paste! {
            impl<$( '[< $ty >], $ty ),*> … { … }
        }
    }
}
```

**Comment by dtolnay** [comment]
It should work as long as you put the `'` inside the `[<`.
`impl<$([<'_ $ty>],)* $($ty,)*> …`.

**Comment by tqwewe** [comment]
Ah okay, it also seems like I have to do `[< '_ $ty >]` instead of just `[< ' $ty >]`

**Comment by dtolnay** [comment]
`[< ' $ty >]` is not lexically valid Rust tokens so rustc wouldn't allow that in macro input.

If you don't want an underscore in the lifetime then you can use `[<"'" $ty>]`.
