### ISSUE TITLE
Possible to use bracket inside a paste expansion?

### ISSUE THREAD

**Issue by bbaldino** [dtolnay/paste#90]
I've got a use case where I need to do something like this:

```
[< <T>::read_ $type>](&buf)
```
And, from what I can tell, it _seems_ like `paste!` might not like the nested brackets.  The error I get when building is:
```
expected one of `(`, `::`, `<`, `>`, or `as`
```

Is this supported and I'm just missing something?  Or is this not possible in `paste!`?

**Comment by dtolnay** [comment]
"\<T\>::read_whatever" is not an identifier in Rust. Whatever you put inside of `[<`…`>]` needs to result in a valid identifier, i.e. something that would be legal to use as the name of a variable.
