### ISSUE TITLE
Cannot use with an expr containing "::": expected identifier after `:`

### ISSUE THREAD

**Issue by awoimbee** [dtolnay/paste#97]
I want to use this crate to template function names that are not in the current module.
It's because I have a weird use-case where I have routes like `get_blob`, `get_blob_2level`, ... [here](https://github.com/Extrality/trow/blob/567ee7ab3548be5b7a40311d5e8fef4e85a03df4/src/routes/blob.rs#L28).

This example speaks for itself:

```rust
/// calls ${fn}(), ${fn}_1(), ${fn}_2()
macro_rules! super_caller {
    ($fn:expr) => {
        paste::paste! {
            $fn();
            [< $fn _1 >]();
            [< $fn _2 >]();
        }
    }
}

fn toto() {}
fn toto_1() {}
fn toto_2() {}

fn main() {
    super_caller!(toto); // OK
    super_caller!(crate::toto); // expected identifier after `:`
}

```

**Comment by dtolnay** [comment]
I think this is working as intended -- `crate::todo_1` is not a valid identifier.
